# Generated by Django 4.1.3 on 2022-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_category_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="products",
            field=models.ManyToManyField(blank=True, to="goods.product"),
        ),
    ]
